title:              Evan A. Perkowski
email:              "<evan.a.perkowski@ttu.edu>"
description:        Evan A. Perkowski's Personal Website
author:             Evan A. Perkowski
baseurl:            "/"
url:                "https://eaperkowski.github.io"

# Social Profiles
twitter_username:   EvanPerkowski
github_username:    eaperkowski
facebook_username:  
instagram_username:  
linkedin_username: evan-a-perkowski

# Add your google-analytics ID here to activate google analytics
google_analytics:   #UA-XXXXXXXXX-X # out your google-analytics code

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-VCJEWCMN68"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-VCJEWCMN68');
</script>

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
