# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Evan A. Perkowski
tagline:          'A Jekyll theme'
description:      'Nutrient acquisition, nutrient allocation, photosynthetic acclimation.'
url:              https://eaperkowski.github.io/


gems:                [jekyll-paginate]
#paginate:            5
paginate_path:       "page:num"

author:
  name:           'Evan A. Perkowski'
  url:            https://twitter.com/evanperkowski

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
