# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://eaperkowski.github.io'
baseurl: ''
title: 'Evan Perkowski'
description: 'Personal website for Evan Perkowski'
permalink: pretty
logo: "https://www.gravatar.com/avatar/f5f7108c8e7e4c58af326e925b1f588f"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About Me
  url: /about/
- title: Current Research
  url: /research/
- title: Curriculum Vitae
  url: /cv/
- title: News
  url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: News
    output: true
    feature_image: ["/files/pine.jpeg"]
